### ISSUE TITLE
unable to see home folder

### ISSUE THREAD

**Issue by alculete** [albertodonato/sonarr-snap#1]
Installed sonarr and I'm unable to add my `home/user` folder, I can't see any folder
![image](https://user-images.githubusercontent.com/2129497/51317667-e0ab0e00-1a60-11e9-808c-1e5ed84dc85f.png)

**EDIT:** Going through your `yaml` it seems is missing the `home` plug

**Comment by albertodonato** [comment]
Adding the `home` plug has no effect as the application runs as `daemon`, and thus as a confied root user. A root user in a snap can't access user home dirs.

Storage foleders for downloads should be set either under `/var/snap/sonarr/common` or under `/media`, after connecting the `removable-media` interface (which doesn't get autoconnected).

I've added this to the  README.

**Comment by alculete** [comment]
@albertodonato any plans for radarr and lidarr?
