### ISSUE TITLE
How to update Sonarr?

### ISSUE THREAD

**Issue by Critter** [albertodonato/sonarr-snap#10]
Sonarr keeps telling me there is an update available, but Snap tells me there is nothing available to update. Do you have any suggestions on how to get to the latest version?

**Comment by albertodonato** [comment]
Right now the snap can't use the sonarr self-update functionality, due to the file tree being read-only.

I've built a new snap with the latest versions, it should auto-update (or you can force it with `sudo snap update sonarr`.

**Comment by Critter** [comment]
oi mate. Any chance you could build a new snap for the current update?

cheers.
