### ISSUE TITLE
Why does this run as root?

### ISSUE THREAD

**Issue by fryfrog** [albertodonato/sonarr-snap#2]
^ See title.

**Comment by albertodonato** [comment]
Daemons in snaps run as user id 0, but they are confined, so the "root" user inside the snap won't have any permission beyond what defined in the snap itself via plugs.

This works similarly as Docker, where apps also run as confined root

**Comment by fryfrog** [comment]
I haven't used *all* the Docker images, but I've *literally* never run into one that runs as `root`. Inside, they typically run as `nobody` or `abc` (but the name doesn't matter), where they're passed a UID/GID that typically defaults to something like 100.

I don't know anything about Snap, but I'm going to go out on a limb and say I doubt they run as `root` unless they're doing something that requires it.

**Comment by fryfrog** [comment]
Is it possible that it actually runs as the user you run the snap as? And since your directions are using `sudo`, it is running as `root`? I don't see anything in your yaml that even mentions root.

**Comment by fryfrog** [comment]
> 08:30 < Chipaca> fryfrog: daemons that come in snaps run as uid 0 for now, yes

From IRC, you're right.
