### ISSUE TITLE
request: Create radarr snap

### ISSUE THREAD

**Issue by alculete** [albertodonato/sonarr-snap#3]
@albertodonato  could you package radarr as a snap also?

**Comment by chest069** [comment]
I also would like to see a radarr-snap be made

**Comment by kinekt4** [comment]
Hi @albertodonato,

I just want to let you know my intention to create a snap for radarr.

I've created a fork off your project and renamed it radarr-snap:

https://github.com/kinekt4/radarr-snap

Let me know if you think there may be any issues with this. Thanks

**Comment by albertodonato** [comment]
Hi @kinekt4,

no issue at all, happy that this repo can serve as a base for the radarr snap.

I'll then close this issue.

Thanks

**Comment by kinekt4** [comment]
Happy to hear it. Thank you!
