### ISSUE TITLE
Sonarr shows not enough space while there still space

### ISSUE THREAD

**Issue by alculete** [albertodonato/sonarr-snap#4]
I get an warning of no space but I still have space

**Comment by albertodonato** [comment]
This is likely a sonarr issue (not specific to the snap), but could you give some more details?

**Comment by alculete** [comment]
this is what it is shown, I still have 168 GB free
![image](https://user-images.githubusercontent.com/2129497/56863297-f95a8680-69b4-11e9-8f0f-8dd7ae31deb1.png)

this is from my radarr deb. sonarr deb also showed remaining space

![image](https://user-images.githubusercontent.com/2129497/56863313-2149ea00-69b5-11e9-8651-c2ea7b866a20.png)

**Comment by albertodonato** [comment]
could you paste the output of `df -h`?

**Comment by alculete** [comment]
```
Filesystem                       Size  Used Avail Use% Mounted on
udev                             3.9G     0  3.9G   0% /dev
tmpfs                            787M  2.8M  784M   1% /run
/dev/mapper/prometheus--vg-root  1.8T  1.6T  169G  91% /
tmpfs                            3.9G  860K  3.9G   1% /dev/shm
tmpfs                            5.0M     0  5.0M   0% /run/lock
tmpfs                            3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0                        31M   31M     0 100% /snap/sonarr/112
/dev/loop1                        98M   98M     0 100% /snap/docker/321
/dev/loop8                       256K  256K     0 100% /snap/gtk2-common-themes/4
/dev/loop2                        12M   12M     0 100% /snap/speed-test/21
/dev/loop10                       13M   13M     0 100% /snap/speed-test/31
/dev/loop14                       89M   89M     0 100% /snap/plexmediaserver/13
/dev/loop3                       172M  172M     0 100% /snap/filebot/24
/dev/loop6                        98M   98M     0 100% /snap/docker/355
/dev/loop13                      7.5M  7.5M     0 100% /snap/canonical-livepatch/74
/dev/loop16                      7.5M  7.5M     0 100% /snap/canonical-livepatch/69
/dev/loop15                      171M  171M     0 100% /snap/filebot/9
/dev/loop7                        92M   92M     0 100% /snap/core/6531
/dev/loop5                        54M   54M     0 100% /snap/core18/941
/dev/loop11                       91M   91M     0 100% /snap/core/6405
/dev/loop19                       90M   90M     0 100% /snap/core/6673
/dev/loop17                      7.5M  7.5M     0 100% /snap/canonical-livepatch/71
/dev/loop18                       91M   91M     0 100% /snap/plexmediaserver/11
/dev/loop12                      196M  196M     0 100% /snap/filebot/16
/dev/loop4                        36M   36M     0 100% /snap/gtk-common-themes/1198
/dev/loop9                        91M   91M     0 100% /snap/plexmediaserver/8
tmpfs                            787M     0  787M   0% /run/user/1000
```

**Comment by albertodonato** [comment]
I think the reason is that the `/` seen from the snap is the core (specifically `core18` here) snap, and the filesystem there is a readonly image. This is because of the snap confinement.
It that causing any issue to you?

**Comment by alculete** [comment]
Actually, it is not.
I just reported for you to know.
I've opened a request also, I couldn't find another way to contact so a created an issue

**Comment by alculete** [comment]
@albertodonato I noticed that sometimes downloads are not always imported because of the message that there is no space

**Comment by albertodonato** [comment]
This should be fixed now in the edge channel. It still requires manually connecting the interface via:

```
sudo snap connect sonarr:mount-observe
```

I'll ask if it can be made autoconnect on the store.

**Comment by alculete** [comment]
Just a curiosity, are your updates following the releases from  [sonarr](https://github.com/Sonarr/Sonarr/releases)? If they update you will update almost on the same time?

**Comment by albertodonato** [comment]
Yeah, unfortunately there's no automated process for that, I have a
check-version script in the repo which checks if there are new versions.

I usually try to update it when I notice a new version is reported from my
sonarr install.

**Comment by alculete** [comment]
now it shows  unnecessary information 

![image](https://user-images.githubusercontent.com/2129497/58946655-b0051000-8786-11e9-9f7e-cc7aa4551602.png)

The image below is from radarr.deb

![image](https://user-images.githubusercontent.com/2129497/58946715-d165fc00-8786-11e9-8afa-84ff018f25eb.png)

There was a [ticket](https://github.com/Sonarr/Sonarr/issues/2743) solved related on sonarr github

**Comment by albertodonato** [comment]
Well that's what the system shows, ISTR there was a bug open in sonarr
about not showing some mounts.
Maybe sonarr should try to detect which mounts are actually disks and
exclude bind mounts.

**Comment by alculete** [comment]
> Well that's what the system shows, ISTR there was a bug open in sonarr

yes and it was solved on sonarr

**Comment by albertodonato** [comment]
This
https://github.com/Sonarr/Sonarr/commit/6698ca400c7d5bba407adbb4fe655520096122e0
seems
what you're refering to, but it only filters out mountpoints that start
with /var/lib or /snap.
It should probably look at the type of the mount, and exclude bind mounts
too.
Maybe you could reopen that bug or open a new one?

**Comment by alculete** [comment]
No need. I noticed that only radarr shows only one mount point, sonarr.deb also have that list of unecessary mounts. I will test your new release and report if I find and error. Do I have to mount media and mount-observe everytime I reboot my system?
