### ISSUE TITLE
why can't i restore from backup?

### ISSUE THREAD

**Issue by JediBrooker** [albertodonato/sonarr-snap#5]
I have a backup file that i want to restore but the restore option is not there!

**Comment by albertodonato** [comment]
I don't have first-hand experience with restoring Sonarr backups, but according to https://github.com/Sonarr/Sonarr/wiki/Backup-and-Restore#restoring-from-backup it's done manually by coping the backup files in the AppData dir. Note that the AppData directory for the snap is `/var/snap/sonarr/common/`.
