### ISSUE TITLE
unable to import from sabnzbd snap

### ISSUE THREAD

**Issue by JediBrooker** [albertodonato/sonarr-snap#6]
how do i set permissions to get the sonarr and sabnzbd snaps to talk nicely to each other?

**Comment by albertodonato** [comment]
This is not really a snap-related question. Assuming you have both applications running, you can configure Sonarr to connect to Sabnzbd by adding it as a download client in Settings -> Download Client

**Comment by JediBrooker** [comment]
well, because ive just downloaded an episode of a certain tv show, sabnzbd grabbed it ok, sonarr reported ok that sabnzbd was downloading it. however when it finished downloading sonarr could not import it. it's like sonarr couldn't see or access the download directory of sabnzbd. so to test i chmod the directory and files to 777 but sonarr still couldn't import.

**Comment by albertodonato** [comment]
Ah, I see. The sonarr snap can be connected to the `removable-media` interface, which gives access to `/media`. I'm not sure about the other snap. If it also has that interface, it should be possible to set up a "shared" directory under there that they can both access.
