### ISSUE TITLE
How do I fix this error sonarr

### ISSUE THREAD

**Issue by chest069** [albertodonato/sonarr-snap#7]
Hello,
I just found and install your snap for sonarr. When going through setting everything up on my system I get the following error : Cannot install update because startup folder '/snap/sonarr/184/NzbDrone' is not writable by the user 'root'.

How can I fix this because I am also unable to point to a directory on my hard drive in my home folder as to where to find my files and videos.

Thanks for any help.

**Comment by albertodonato** [comment]
Hi,
the snap can't be updated via the UI, since it's not writable. I usually release a new snap version when I notice a new sonarr version, but AFAICS 2.0.0.5338 is the latest, which is what is currently released for the stable snap. What version are you trying to udpate?

**Comment by chest069** [comment]
Hello,
Thanks for getting back to me. I was trying to run it with the internal update for sonarr on.
The only other thing was getting it to point to the folders I wish to use for it (where my media files are) it doesn't see them and other than that great job and thanks again for making it.

**Comment by albertodonato** [comment]
For media folders, see https://github.com/albertodonato/sonarr-snap#setting-storage-path-for-downloads 

Basically you have to connect the interfaces, and media folders must be localted under `/media`.

**Comment by pcconceptsja** [comment]
> For media folders, see https://github.com/albertodonato/sonarr-snap#setting-storage-path-for-downloads
> 
> Basically you have to connect the interfaces, and media folders must be localted under `/media`.

ho can i access a /mnt folder

**Comment by albertodonato** [comment]
> ho can i access a /mnt folder

You can't access folders under `/mnt` as the snap confinement won't allow it.
If possible, you should try to mount it under `/media` instead
