### ISSUE TITLE
How to update with Snap on Fedora 31?

### ISSUE THREAD

**Issue by BWBama85** [albertodonato/sonarr-snap#8]
Can you provide the method to update Sonarr on Fedora 31 using this? I am unable to do it through the interface because sonarr does not have permission to write to the install directory. There is an important update that I am unable to access.

**Comment by albertodonato** [comment]
Snaps automatically check for updates periodically, and automatically update.
You can force an update (if there is one) via `sudo snap refresh sonarr`.

Can you paste the output of `snap info sonarr`?

**Comment by albertodonato** [comment]
I'm closing this as I don't think there's anything wrong with the snap. Please reopen and add the request info if you're still experiencing the issue.
