### ISSUE TITLE
Snap Path Invalid Path 

### ISSUE THREAD

**Issue by urbandroid** [albertodonato/sonarr-snap#9]
When installed with snap since sonarr directory is read only can't add path new series.

ame: sonarr
summary: Smart PVR for newsgroup and bittorrent users
publisher: Alberto Donato (ack)
store-url: https://snapcraft.io/sonarr
contact: https://github.com/albertodonato/sonarr-snap
license: GPL-3.0+
description: |
Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple
RSS
feeds for new episodes of your favorite shows and will grab, sort and
rename
them. It can also be configured to automatically upgrade the quality of
files
already downloaded when a better quality format becomes available.

The web interface is accessible by default at http://localhost:8989

See https://sonarr.tv for more details.
services:
sonarr.nzbdrone: simple, enabled, active
snap-id: TSZAyHNSnTl1RyVD6AcCYH53XVwxIjGX
tracking: latest/stable
refresh-date: today at 05:00 +03
channels:
latest/stable: 2.0.0.5344 2020-03-21 (225) 31MB -
latest/candidate: ↑
latest/beta: ↑
latest/edge: 2.0.0.5344 2020-04-23 (237) 31MB -
installed: 2.0.0.5344 (225) 31MB -

clean install

**Comment by albertodonato** [comment]
You can select paths under `/var/snap/sonarr/comon` for download, or, by connecting the `removable-media` interface, paths under `/media` as well.

The target path must be owned by root.

**Comment by urbandroid** [comment]
sonarr snap doesn't create that path and no! no snap need to access to access removable media nevermind your snap sucks.

**Comment by albertodonato** [comment]
You have to create the desired path yourself (sonar lets you pick different download path for different series).

As for `/media`, it can be used to share files between snaps (e.g. between sonarr and transmission-daemon).

**Comment by RSkotte** [comment]
@urbandroid I agree with you, cannot add any series because it cannot create the local folder for download. I have used removable-media but it simply doesn't work whatever I do. Can only see some basic system folders but no media folder or anything else to "write" to.
